# ***IntelliHack***

## **Hackathon Problem Statements On AI in Cybersecurity**

----

### *Problem Statement - 4*

**Problem Statement:** AI for Real-Time Fraud & Social Engineering Detection

***Description of the Problem:*** Industries, particularly financial services, are losing billions of dollars to social engineering scams, such as fake investment schemes and fraudulent calls. The problem is to create an AI system that can analyze live text or audio conversations to detect and warn against suspicious patterns and phrases.

* **Expectation form Prototype -**
   * An AI-driven assistant that analyzes live text/audio conversations.

   * A model that can detect urgency phrases or suspicious transaction  patterns.

   * A real-time warning system to alert users of potential fraud.

### **Prototype Name :-**

#### **AlertX – Emphasizes Financial Security**

*Built-up by AI Devilops*

Team Lead :- Deepak Kaura

Other member :- Vivek Nayi

* ***Note - It's all about BERT Classiication (NLP) + LLM integration also includes Gradio (deployment)***

In [ ]:
#import pandas as pd


#data = pd.read_csv("fraud_call.file",sep='\t',names=['label','content'], on_bad_lines='skip')

In [ ]:
#data.to_csv('fraud call fin.csv', index=False)

## **Loading Important Libraries**

In [ ]:
import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from transformers import BertTokenizer, BertModel
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
#from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
import plotly.figure_factory as ff



data_df = pd.read_csv('fraud call fin.csv')

### **Checking first 5 rows**

In [ ]:
data_df.head()

   label                                            content
0      1  hello, i m bank manager of SBI, ur debit card ...
1      1  Todays Vodafone numbers ending with 4882 are s...
2      0               Please don't say like that. Hi hi hi
3      0                                         Thank you!
4      0  Oh that was a forwarded message. I thought you...

### **Checking each column/feature datatype**

In [ ]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5924 entries, 0 to 5923
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5924 non-null   int64
 1   content  5924 non-null   object
dtypes: int64(1), object(1)
memory usage: 92.7+ KB

### **Checking target column value counts**

In [ ]:
data_df.label.value_counts()

label
0    5286
1     638
Name: count, dtype: int64

## **Time To build BERT model**

In [ ]:

# ===============================
# 1. Load data
# ===============================
y = data_df['label'].values

In [ ]:
# ===============================
# 2. Load BERT model
# ===============================
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert = BertModel.from_pretrained("bert-base-uncased")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert.to(device)
bert.eval()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [ ]:
# ===============================
# 3. Extract BERT embeddings (CLS)
# ===============================
def get_embeddings(texts, batch_size=16, max_len=128):
    all_embeds = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(batch, padding=True, truncation=True, max_length=max_len, return_tensors="pt")
        input_ids = enc["input_ids"].to(device)
        attn_mask = enc["attention_mask"].to(device)
        with torch.no_grad():
            outputs = bert(input_ids, attention_mask=attn_mask)
            cls_embeds = outputs.last_hidden_state[:,0,:]  # CLS token
            all_embeds.append(cls_embeds.cpu().numpy())
    return np.vstack(all_embeds)

X = get_embeddings(data_df["content"].tolist())

In [ ]:
# ===============================
# 4. Define classifier head
# ===============================
num_labels = len(set(y))
classifier = nn.Sequential(
    nn.Linear(X.shape[1], 256),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(256, num_labels)
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(classifier.parameters(), lr=2e-5)

In [ ]:

# =====================================================
# 5. Get embeddings, labels, and raw text
# =====================================================
                   # numeric labels
texts = data_df["content"].values                # original sentences

# =====================================================
# 6. Split indices first (so everything aligns)
# =====================================================
indices = np.arange(len(X))
train_idx, test_idx = train_test_split(
    indices, test_size=0.2, stratify=y, random_state=42
)

# Slice embeddings, labels, and texts with the same indices
X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]
text_train, text_test = texts[train_idx], texts[test_idx]

# =====================================================
# 7. Apply SMOTE on training embeddings only
# =====================================================
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# =====================================================
# 8. Create DataLoaders
# =====================================================
train_dataset = TensorDataset(torch.tensor(X_train_res, dtype=torch.float32),
                              torch.tensor(y_train_res, dtype=torch.long))

test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                             torch.tensor(y_test, dtype=torch.long))

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# =====================================================
# 9. Training loop
# =====================================================
epochs = 5
for epoch in range(epochs):
    classifier.train()
    total_loss = 0
    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        logits = classifier(xb)
        loss = criterion(logits, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss/len(train_loader):.4f}")

# =====================================================
# 10. Evaluation loop
# =====================================================
classifier.eval()
all_preds, all_labels = [], []
with torch.no_grad():
    for xb, yb in test_loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = classifier(xb)
        preds = torch.argmax(logits, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(yb.cpu().numpy())

# =====================================================
# 11. Accuracy
# =====================================================
print('----' * 16)
print(f"✅ BERT Classifier Accuracy: {accuracy_score(all_labels, all_preds):.2f}")
print('----' * 16)

# =====================================================
# 12. Confusion Matrix
# =====================================================
cm = confusion_matrix(all_labels, all_preds)

# If you have label names, use them here
labels = ['Normal', 'Farud']   # <-- replace with your class names
z_text = [[str(y) for y in x] for x in cm]

fig = ff.create_annotated_heatmap(
    z=cm,
    x=labels,  # Predicted
    y=labels,  # True
    annotation_text=z_text,
    colorscale='Blues',
    showscale=True
)

fig.update_layout(
    title_text='Confusion Matrix - BERT Classifier',
    width=550,
    height=500
)

fig['data'][0]['showscale'] = True
fig.show()

Epoch 1/5 - Loss: 0.0793
Epoch 2/5 - Loss: 0.0724
Epoch 3/5 - Loss: 0.0680
Epoch 4/5 - Loss: 0.0643
Epoch 5/5 - Loss: 0.0620
----------------------------------------------------------------
✅ BERT Classifier Accuracy: 0.96
----------------------------------------------------------------

In [ ]:
# =====================================================
# 13. Build results DataFrame with original content
# =====================================================
results_llm = pd.DataFrame({
    "content": text_test,          # original text (aligned by indices)

    "predicted_label": all_preds   # predictions
})

results_llm.head()

                                             content  predicted_label
0  you have a secret admirer. REVEAL who thinks y...                1
1  He is impossible to argue with and he always t...                0
2  Shuhui has bought ron's present it's a swatch ...                0
3  Aight I've been set free, think you could text...                0
4  Cool, we shall go and see, have to go to tip a...                0

In [ ]:
results_llm.to_csv('results_llm_fraud_calls.csv', index=False)

## **Time for utilizing Test data on LLM**

In [ ]:
import pandas as pd

results_llm_df = pd.read_csv('results_llm_fraud_calls.csv')

In [ ]:
# Apply categorization directly on results_llm
def categorize_sms(text, label):
    if label == 0:
        return "Normal SMS"

    text = str(text).lower()
    if any(w in text for w in ["win", "prize", "reward", "lottery", "lucky", "cash"]):
        return "Lottery Scam"
    elif any(w in text for w in ["loan", "bank", "credit", "account", "card", "insurance"]):
        return "Financial Scam"
    elif any(w in text for w in ["love", "admirer", "dating", "chat", "sexy"]):
        return "Romance Scam"
    elif any(w in text for w in ["free", "ringtone", "offer", "call", "sms"]):
        return "Promotion/Spam"
    else:
        return "Other Fraud"

# Create a new column with category labels
results_llm_df["category"] = results_llm_df.apply(
    lambda row: categorize_sms(row["content"], row["predicted_label"]), axis=1
)

# Preview
print(results_llm_df.head(10))

                                             content  predicted_label  \
0  you have a secret admirer. REVEAL who thinks y...                1
1  He is impossible to argue with and he always t...                0
2  Shuhui has bought ron's present it's a swatch ...                0
3  Aight I've been set free, think you could text...                0
4  Cool, we shall go and see, have to go to tip a...                0
5  It’s been really long we guys haven’t gone any...                0
6    I finished my lunch already. U wake up already?                0
7  No de. But call me after some time. Ill tell y...                0
8  Awesome question with a cute answer: Someone a...                0
9           Is this the house you wanted to show us?                0

       category
0  Romance Scam
1    Normal SMS
2    Normal SMS
3    Normal SMS
4    Normal SMS
5    Normal SMS
6    Normal SMS
7    Normal SMS
8    Normal SMS
9    Normal SMS

In [ ]:
!pip install langchain

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (0.3.27)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.72 in /usr/local/lib/python3.12/dist-packages (from langchain) (0.3.75)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from langchain) (0.3.11)
Requirement already satisfied: langsmith>=0.1.17 in /usr/local/lib/python3.12/dist-packages (from langchain) (0.4.24)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.11.7)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.0.43)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.32.4)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.12/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (8.5.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (4.15.0)
Requirement already satisfied: packaging>=23.2 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (25.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (0.24.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (2025.8.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (4.10.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.72->langchain) (3.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.3.1)

In [ ]:
!pip install txtai

Collecting txtai[pipeline]
  Downloading txtai-9.0.0-py3-none-any.whl.metadata (31 kB)
Collecting faiss-cpu>=1.7.1.post2 (from txtai[pipeline])
  Downloading faiss_cpu-1.12.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: msgpack>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (1.1.1)
Requirement already satisfied: torch>=2.1 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (2.8.0+cu126)
Requirement already satisfied: transformers>=4.45.0 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (4.56.1)
Requirement already satisfied: huggingface-hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (0.34.4)
Requirement already satisfied: numpy>=1.18.4 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (2.0.2)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (6.0.2)
Requirement already satisfied: regex>=2022.8.17 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (2024.11.6)
Requirement already satisfied: safetensors>=0.4.5 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (0.6.2)
Collecting onnx>=1.11.0 (from txtai[pipeline])
  Downloading onnx-1.19.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (7.0 kB)
Collecting onnxruntime>=1.11.0 (from txtai[pipeline])
  Downloading onnxruntime-1.22.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (1.16.1)
Collecting sounddevice>=0.5.0 (from txtai[pipeline])
  Downloading sounddevice-0.5.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: soundfile>=0.10.3.post1 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (0.13.1)
Collecting ttstokenizer>=1.1.0 (from txtai[pipeline])
  Downloading ttstokenizer-1.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting webrtcvad-wheels>=2.0.14 (from txtai[pipeline])
  Downloading webrtcvad_wheels-2.0.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: beautifulsoup4>=4.9.3 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (4.13.5)
Collecting chonkie>=1.0.2 (from txtai[pipeline])
  Downloading chonkie-1.2.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (24 kB)
Collecting docling>=2.8.2 (from txtai[pipeline])
  Downloading docling-2.52.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: nltk>=3.5 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (3.9.1)
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (2.2.2)
Collecting tika>=1.24 (from txtai[pipeline])
  Downloading tika-3.1.0-py3-none-any.whl.metadata (15 kB)
Collecting imagehash>=4.2.1 (from txtai[pipeline])
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (11.3.0)
Requirement already satisfied: timm>=0.4.12 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (1.0.19)
Collecting litellm>=1.37.16 (from txtai[pipeline])
  Downloading litellm-1.77.0-py3-none-any.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 3.4 MB/s eta 0:00:00
Collecting llama-cpp-python>=0.2.75 (from txtai[pipeline])
  Downloading llama_cpp_python-0.3.16.tar.gz (50.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 MB 20.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gliner>=0.2.16 (from txtai[pipeline])
  Downloading gliner-0.2.22-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: sentencepiece>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (0.2.1)
Collecting staticvectors>=0.2.0 (from txtai[pipeline])
  Downloading staticvectors-0.2.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: accelerate>=0.26.0 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (1.10.1)
Collecting bitsandbytes>=0.42.0 (from txtai[pipeline])
  Downloading bitsandbytes-0.47.0-py3-none-manylinux_2_24_x86_64.whl.metadata (11 kB)
Collecting onnxmltools>=1.9.1 (from txtai[pipeline])
  Downloading onnxmltools-1.14.0-py2.py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: peft>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from txtai[pipeline]) (0.17.1)
Collecting skl2onnx>=1.9.1 (from txtai[pipeline])
  Downloading skl2onnx-1.19.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.26.0->txtai[pipeline]) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.26.0->txtai[pipeline]) (5.9.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.9.3->txtai[pipeline]) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.9.3->txtai[pipeline]) (4.15.0)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from chonkie>=1.0.2->txtai[pipeline]) (4.67.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from docling>=2.8.2->txtai[pipeline]) (2.11.7)
Collecting docling-core<3.0.0,>=2.48.0 (from docling-core[chunking]<3.0.0,>=2.48.0->docling>=2.8.2->txtai[pipeline])
  Downloading docling_core-2.48.1-py3-none-any.whl.metadata (6.5 kB)
Collecting docling-parse<5.0.0,>=4.4.0 (from docling>=2.8.2->txtai[pipeline])
  Downloading docling_parse-4.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.5 kB)
Collecting docling-ibm-models<4,>=3.9.1 (from docling>=2.8.2->txtai[pipeline])
  Downloading docling_ibm_models-3.9.1-py3-none-any.whl.metadata (6.7 kB)
Collecting filetype<2.0.0,>=1.2.0 (from docling>=2.8.2->txtai[pipeline])
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting pypdfium2!=4.30.1,<5.0.0,>=4.30.0 (from docling>=2.8.2->txtai[pipeline])
  Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: pydantic-settings<3.0.0,>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from docling>=2.8.2->txtai[pipeline]) (2.10.1)
Requirement already satisfied: requests<3.0.0,>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from docling>=2.8.2->txtai[pipeline]) (2.32.4)
Collecting easyocr<2.0,>=1.7 (from docling>=2.8.2->txtai[pipeline])
  Downloading easyocr-1.7.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from docling>=2.8.2->txtai[pipeline]) (2025.8.3)
Collecting rtree<2.0.0,>=1.3.0 (from docling>=2.8.2->txtai[pipeline])
  Downloading rtree-1.4.1-py3-none-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Collecting typer<0.17.0,>=0.12.5 (from docling>=2.8.2->txtai[pipeline])
  Downloading typer-0.16.1-py3-none-any.whl.metadata (15 kB)
Collecting python-docx<2.0.0,>=1.1.2 (from docling>=2.8.2->txtai[pipeline])
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting python-pptx<2.0.0,>=1.0.2 (from docling>=2.8.2->txtai[pipeline])
  Downloading python_pptx-1.0.2-py3-none-any.whl.metadata (2.5 kB)
Collecting marko<3.0.0,>=2.1.2 (from docling>=2.8.2->txtai[pipeline])
  Downloading marko-2.2.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: openpyxl<4.0.0,>=3.1.5 in /usr/local/lib/python3.12/dist-packages (from docling>=2.8.2->txtai[pipeline]) (3.1.5)
Requirement already satisfied: lxml<6.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from docling>=2.8.2->txtai[pipeline]) (5.4.0)
Requirement already satisfied: pluggy<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from docling>=2.8.2->txtai[pipeline]) (1.6.0)
Collecting pylatexenc<3.0,>=2.10 (from docling>=2.8.2->txtai[pipeline])
  Downloading pylatexenc-2.10.tar.gz (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 9.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting polyfactory>=2.22.2 (from docling>=2.8.2->txtai[pipeline])
  Downloading polyfactory-2.22.2-py3-none-any.whl.metadata (27 kB)
Collecting transformers>=4.45.0 (from txtai[pipeline])
  Downloading transformers-4.51.0-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->txtai[pipeline]) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->txtai[pipeline]) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.34.0->txtai[pipeline]) (1.1.9)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash>=4.2.1->txtai[pipeline]) (1.9.0)
Requirement already satisfied: aiohttp>=3.10 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (3.12.15)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (8.2.1)
Collecting fastuuid>=0.12.0 (from litellm>=1.37.16->txtai[pipeline])
  Downloading fastuuid-0.12.0-cp312-cp312-manylinux_2_34_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (0.28.1)
Requirement already satisfied: importlib-metadata>=6.8.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (8.7.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (3.1.6)
Requirement already satisfied: jsonschema<5.0.0,>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (4.25.1)
Requirement already satisfied: openai>=1.99.5 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (1.106.1)
Requirement already satisfied: python-dotenv>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (1.1.1)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (0.11.0)
Requirement already satisfied: tokenizers in /usr/local/lib/python3.12/dist-packages (from litellm>=1.37.16->txtai[pipeline]) (0.22.0)
Collecting diskcache>=5.6.1 (from llama-cpp-python>=0.2.75->txtai[pipeline])
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.5->txtai[pipeline]) (1.5.2)
Requirement already satisfied: protobuf>=4.25.1 in /usr/local/lib/python3.12/dist-packages (from onnx>=1.11.0->txtai[pipeline]) (5.29.5)
Requirement already satisfied: ml_dtypes in /usr/local/lib/python3.12/dist-packages (from onnx>=1.11.0->txtai[pipeline]) (0.5.3)
Collecting coloredlogs (from onnxruntime>=1.11.0->txtai[pipeline])
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.11.0->txtai[pipeline]) (25.2.10)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.11.0->txtai[pipeline]) (1.13.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.0->txtai[pipeline]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.0->txtai[pipeline]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.0->txtai[pipeline]) (2025.2)
Requirement already satisfied: scikit-learn>=1.1 in /usr/local/lib/python3.12/dist-packages (from skl2onnx>=1.9.1->txtai[pipeline]) (1.6.1)
Requirement already satisfied: CFFI>=1.0 in /usr/local/lib/python3.12/dist-packages (from sounddevice>=0.5.0->txtai[pipeline]) (1.17.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tika>=1.24->txtai[pipeline]) (75.2.0)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from timm>=0.4.12->txtai[pipeline]) (0.23.0+cu126)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (3.5)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1->txtai[pipeline]) (3.4.0)
Collecting tokenizers (from litellm>=1.37.16->txtai[pipeline])
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting anyascii>=0.3.1 (from ttstokenizer>=1.1.0->txtai[pipeline])
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: inflect>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from ttstokenizer>=1.1.0->txtai[pipeline]) (7.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10->litellm>=1.37.16->txtai[pipeline]) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10->litellm>=1.37.16->txtai[pipeline]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10->litellm>=1.37.16->txtai[pipeline]) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10->litellm>=1.37.16->txtai[pipeline]) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10->litellm>=1.37.16->txtai[pipeline]) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10->litellm>=1.37.16->txtai[pipeline]) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10->litellm>=1.37.16->txtai[pipeline]) (1.20.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from CFFI>=1.0->sounddevice>=0.5.0->txtai[pipeline]) (2.22)
Collecting jsonref<2.0.0,>=1.1.0 (from docling-core<3.0.0,>=2.48.0->docling-core[chunking]<3.0.0,>=2.48.0->docling>=2.8.2->txtai[pipeline])
  Downloading jsonref-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from docling-core<3.0.0,>=2.48.0->docling-core[chunking]<3.0.0,>=2.48.0->docling>=2.8.2->txtai[pipeline]) (0.9.0)
Collecting latex2mathml<4.0.0,>=3.77.0 (from docling-core<3.0.0,>=2.48.0->docling-core[chunking]<3.0.0,>=2.48.0->docling>=2.8.2->txtai[pipeline])
  Downloading latex2mathml-3.78.1-py3-none-any.whl.metadata (15 kB)
Collecting semchunk<3.0.0,>=2.2.0 (from docling-core[chunking]<3.0.0,>=2.48.0->docling>=2.8.2->txtai[pipeline])
  Downloading semchunk-2.2.2-py3-none-any.whl.metadata (10 kB)
Collecting jsonlines<4.0.0,>=3.1.0 (from docling-ibm-models<4,>=3.9.1->docling>=2.8.2->txtai[pipeline])
  Downloading jsonlines-3.1.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: opencv-python-headless<5.0.0.0,>=4.6.0.66 in /usr/local/lib/python3.12/dist-packages (from docling-ibm-models<4,>=3.9.1->docling>=2.8.2->txtai[pipeline]) (4.12.0.88)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from easyocr<2.0,>=1.7->docling>=2.8.2->txtai[pipeline]) (0.25.2)
Collecting python-bidi (from easyocr<2.0,>=1.7->docling>=2.8.2->txtai[pipeline])
  Downloading python_bidi-0.6.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: Shapely in /usr/local/lib/python3.12/dist-packages (from easyocr<2.0,>=1.7->docling>=2.8.2->txtai[pipeline]) (2.1.1)
Collecting pyclipper (from easyocr<2.0,>=1.7->docling>=2.8.2->txtai[pipeline])
  Downloading pyclipper-1.3.0.post6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting ninja (from easyocr<2.0,>=1.7->docling>=2.8.2->txtai[pipeline])
  Using cached ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->litellm>=1.37.16->txtai[pipeline]) (4.10.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->litellm>=1.37.16->txtai[pipeline]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->litellm>=1.37.16->txtai[pipeline]) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->litellm>=1.37.16->txtai[pipeline]) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata>=6.8.0->litellm>=1.37.16->txtai[pipeline]) (3.23.0)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.12/dist-packages (from inflect>=0.3.1->ttstokenizer>=1.1.0->txtai[pipeline]) (10.8.0)

In [ ]:
!pip install langchain-community

Collecting langchain-community
  Downloading langchain_community-0.3.29-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.75 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.3.75)
Requirement already satisfied: langchain<2.0.0,>=0.3.27 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.3.27)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.43)
Collecting requests<3,>=2.32.5 (from langchain-community)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.12.15)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (8.5.0)
Collecting dataclasses-json<0.7,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.10.1)
Requirement already satisfied: langsmith>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.24)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.1)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.20.1)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from langchain<2.0.0,>=0.3.27->langchain-community) (0.3.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain<2.0.0,>=0.3.27->langchain-community) (2.11.7)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (4.15.0)
Requirement already satisfied: packaging>=23.2 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (25.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.125->langchain-community) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.125->langchain-community) (0.24.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.5->langchain-community) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.5->langchain-community) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.5->langchain-community) (2025.8.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3,>=1.4->langchain-community) (3.2.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (4.10.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<2.0.0,>=0.3.75->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community) (2.33.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.6.7->langchain-community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (1.3.1)
Downloading langchain_community-0.3.29-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 21.7 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 6.3 MB/s eta 0:00:00
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 4.6 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: requests, mypy-extensions, marshmallow, typing-inspect, dataclasses-json, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
Successfully installed dataclasses-json-0.6.7 langchain-community-0.3.29 marshmallow-3.26.1 mypy-extensions-1.1.0 requests-2.32.5 typing-inspect-0.9.0

In [ ]:

from txtai import LLM

txtai = LLM("MaziyarPanahi/gemma-2-2b-it-GGUF/gemma-2-2b-it.Q8_0.gguf")

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

gemma-2-2b-it.Q8_0.gguf:   0%|          | 0.00/2.78G [00:00<?, ?B/s]

llama_kv_cache_unified_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)

## ***Deployment : Gradio***

*Final stage: Testing our LLM-powered alert system with real data via the UI*

In [ ]:
import gradio as gr
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain.schema import StrOutputParser
from txtai.pipeline import LLM




llm = TxtaiLangChainLLM()

# ===============================
# 2. Rule-based fraud categorizer
# ===============================
def categorize_sms(text):
    text = str(text).lower()

    if any(w in text for w in ["win", "prize", "reward", "lottery", "lucky", "cash"]):
        return "Lottery Scam"
    elif any(w in text for w in ["loan", "bank", "credit", "account", "card", "insurance"]):
        return "Financial Scam"
    elif any(w in text for w in ["love", "admirer", "dating", "chat", "sexy"]):
        return "Romance Scam"
    elif any(w in text for w in ["free", "ringtone", "offer", "call", "sms"]):
        return "Promotion/Spam"
    elif any(w in text for w in ["customer care", "support", "helpline", "service center", "toll free", "call us"]):
        return "Customer Care Scam"
    else:
        return "Normal SMS"

# ===============================
# 3. Rule-based Alert Messages
# ===============================
def fraud_alert_message(content, category):
    if category == "Normal SMS":
        return "✅ This SMS appears safe and normal."
    elif category == "Lottery Scam":
        return f"⚠️ Fraud Alert: Lottery Scam.\nSMS: {content}\nRecommended Action: Ignore and delete. Never share personal or financial details."
    elif category == "Financial Scam":
        return f"⚠️ Fraud Alert: Financial Scam.\nSMS: {content}\nRecommended Action: Do not click any links or share banking details."
    elif category == "Romance Scam":
        return f"⚠️ Fraud Alert: Romance Scam.\nSMS: {content}\nRecommended Action: Do not respond. Scammers may attempt emotional manipulation."
    elif category == "Promotion/Spam":
        return f"⚠️ Fraud Alert: Promotion/Spam.\nSMS: {content}\nRecommended Action: Block the sender. Do not call or subscribe."
    elif category == "Customer Care Scam":
        return f"⚠️ Fraud Alert: Customer Care Scam.\nSMS: {content}\nRecommended Action: Do not call or trust fake helpline numbers. Always verify from official sources."
    else:
        return f"⚠️ Unknown Category.\nSMS: {content}\nPlease investigate further."

# ===============================
# 4. LLM Explanation
# ===============================
fraud_explain_prompt = PromptTemplate.from_template("""
You are an SMS fraud detection assistant.

SMS Content: {content}
Detected Category: {category}

Explain briefly (in 1-2 sentences) **why this SMS belongs to this fraud category**.
Keep the explanation under 30 words.
""")

fraud_explain_chain = LLMChain(
    llm=llm,
    prompt=fraud_explain_prompt,
    output_parser=StrOutputParser()
)

# ===============================
# 5. Backend Logic
# ===============================
def analyze_sms(user_sms):
    category = categorize_sms(user_sms)
    alert_message = fraud_alert_message(user_sms, category)

    if category != "Normal SMS":
        explanation = fraud_explain_chain.run({
            "content": user_sms,
            "category": category
        })
    else:
        explanation = "This SMS is normal and safe."

    return category, alert_message, explanation

# ===============================
# 6. Gradio UI
# ===============================
with gr.Blocks() as demo:
    gr.Markdown("## 📩 AlertX – Emphasizes Financial Security")

    with gr.Row():
        with gr.Column(scale=1):
            sms_input = gr.Textbox(
                label="Enter SMS Content",
                placeholder="Paste SMS text here...",
                lines=4
            )
            analyze_btn = gr.Button("🔍 Analyze SMS")

        with gr.Column(scale=2):
            category_out = gr.Textbox(label="Fraud Category")
            alert_out = gr.Textbox(label="Alert Message", lines=5)
            explain_out = gr.Textbox(label="Explanation", lines=3)

    analyze_btn.click(
        analyze_sms,
        inputs=[sms_input],
        outputs=[category_out, alert_out, explain_out]
    )

demo.launch()

llama_kv_cache_unified_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)
/tmp/ipython-input-3538800967.py:74: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  fraud_explain_chain = LLMChain(

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://3f1797920b77ea4da8.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)